// FILE: `Backend/routes/search_routes.dart`.
// Purpose: Implements the search routes portion of the streaming service.
// This file is part of the documented Flutter/home-server architecture.
//
// Smart Search is account-authenticated and intentionally read-only.
// Search results are generated by SearchService; this route is responsible
// for transport, authentication, validation, and response handling.

import 'dart:convert';
import 'dart:developer' as developer;
import 'dart:io';

import '../middleware/authentication.dart';
import '../services/search_service.dart';

/// Handles the global Smart Search API.
///
/// Endpoint:
///
///     GET /api/v1/search?q=Spider-Man&limit=50
///
/// Search is authenticated because it is part of the user's
/// streaming service application.
class SearchRoutes {
  final AuthenticationMiddleware authenticationMiddleware;
  final SearchService searchService;

  SearchRoutes({
    required this.authenticationMiddleware,
    required this.searchService,
  });

  static const String _searchPath = '/api/v1/search';

  static const int _defaultLimit = 50;
  static const int _maxLimit = 100;
  static const int _maxQueryLength = 200;

  // ==========================================================
  // REQUEST HANDLER
  // ==========================================================

  Future<void> handle(
    HttpRequest request,
  ) async {
    var responseStarted = false;

    try {
      _applyCors(request.response);

      // --------------------------------------------------------
      // CORS PREFLIGHT
      // --------------------------------------------------------

      if (request.method == 'OPTIONS') {
        responseStarted = true;
        request.response.statusCode = HttpStatus.noContent;
        await request.response.close();
        return;
      }

      // --------------------------------------------------------
      // ROUTE
      // --------------------------------------------------------

      if (request.uri.path != _searchPath) {
        responseStarted = true;

        await _sendJson(
          request.response,
          HttpStatus.notFound,
          {
            'success': false,
            'error': 'Search route not found.',
          },
        );
        return;
      }

      // --------------------------------------------------------
      // METHOD
      // --------------------------------------------------------

      if (request.method != 'GET') {
        responseStarted = true;

        await _sendJson(
          request.response,
          HttpStatus.methodNotAllowed,
          {
            'success': false,
            'error': 'Method not allowed.',
          },
        );
        return;
      }

      // --------------------------------------------------------
      // AUTHENTICATION
      // --------------------------------------------------------

      final account =
          authenticationMiddleware.authenticate(request);

      if (account == null) {
        responseStarted = true;

        await _sendJson(
          request.response,
          HttpStatus.unauthorized,
          {
            'success': false,
            'error': 'Authentication required.',
          },
        );
        return;
      }

      // `account` is intentionally retained here even though the current
      // SearchService API performs a global catalog search. Authentication
      // establishes that the caller is an authorized application user.
      //
      // Future account-scoped/private search can use account.id without
      // changing the HTTP contract.
      final _ = account;

      // --------------------------------------------------------
      // QUERY
      // --------------------------------------------------------

      final rawQuery =
          request.uri.queryParameters['q'];

      if (rawQuery == null) {
        responseStarted = true;

        await _sendJson(
          request.response,
          HttpStatus.badRequest,
          {
            'success': false,
            'error': 'A search query is required.',
          },
        );
        return;
      }

      final query = rawQuery.trim();

      if (query.isEmpty) {
        responseStarted = true;

        await _sendJson(
          request.response,
          HttpStatus.badRequest,
          {
            'success': false,
            'error': 'A search query is required.',
          },
        );
        return;
      }

      if (query.length > _maxQueryLength) {
        responseStarted = true;

        await _sendJson(
          request.response,
          HttpStatus.badRequest,
          {
            'success': false,
            'error':
                'Search query must be $_maxQueryLength characters or fewer.',
          },
        );
        return;
      }

      if (query.contains('\u0000')) {
        responseStarted = true;

        await _sendJson(
          request.response,
          HttpStatus.badRequest,
          {
            'success': false,
            'error': 'Search query contains an invalid character.',
          },
        );
        return;
      }

      // --------------------------------------------------------
      // LIMIT
      // --------------------------------------------------------

      final limitParameter =
          request.uri.queryParameters['limit'];

      var limit = _defaultLimit;

      if (limitParameter != null) {
        final parsedLimit =
            int.tryParse(limitParameter.trim());

        if (parsedLimit == null) {
          responseStarted = true;

          await _sendJson(
            request.response,
            HttpStatus.badRequest,
            {
              'success': false,
              'error': 'limit must be a valid integer.',
            },
          );
          return;
        }

        if (parsedLimit < 1 || parsedLimit > _maxLimit) {
          responseStarted = true;

          await _sendJson(
            request.response,
            HttpStatus.badRequest,
            {
              'success': false,
              'error':
                  'limit must be between 1 and $_maxLimit.',
            },
          );
          return;
        }

        limit = parsedLimit;
      }

      // --------------------------------------------------------
      // SEARCH
      // --------------------------------------------------------

      final results = searchService.search(
        query,
        limit: limit,
      );

      // --------------------------------------------------------
      // RESPONSE
      // --------------------------------------------------------

      responseStarted = true;

      await _sendJson(
        request.response,
        HttpStatus.ok,
        {
          'success': true,
          'query': query,
          'count': results.length,
          'results': results
              .map(
                (result) => result.toJson(),
              )
              .toList(growable: false),
        },
      );
    } on FormatException catch (error, stackTrace) {
      developer.log(
        'Invalid search request.',
        name: 'SearchRoutes',
        error: error,
        stackTrace: stackTrace,
      );

      if (!responseStarted) {
        await _sendJson(
          request.response,
          HttpStatus.badRequest,
          {
            'success': false,
            'error': error.message,
          },
        );
      }
    } catch (error, stackTrace) {
      developer.log(
        'Search request error.',
        name: 'SearchRoutes',
        error: error,
        stackTrace: stackTrace,
      );

      if (!responseStarted) {
        await _sendJson(
          request.response,
          HttpStatus.internalServerError,
          {
            'success': false,
            'error': 'Unable to perform search.',
          },
        );
      }
    }
  }

  // ==========================================================
  // RESPONSE HEADERS
  // ==========================================================

  void _applyCors(HttpResponse response) {
    response.headers.set(
      'Access-Control-Allow-Origin',
      '*',
    );

    response.headers.set(
      'Access-Control-Allow-Methods',
      'GET, OPTIONS',
    );

    response.headers.set(
      'Access-Control-Allow-Headers',
      'Authorization, Content-Type',
    );

    response.headers.set(
      'Access-Control-Expose-Headers',
      'Content-Type',
    );

    response.headers.set(
      'Cache-Control',
      'no-store, no-cache, must-revalidate',
    );

    response.headers.set(
      'Pragma',
      'no-cache',
    );

    response.headers.set(
      'X-Content-Type-Options',
      'nosniff',
    );
  }

  // ==========================================================
  // JSON RESPONSE
  // ==========================================================

  Future<void> _sendJson(
    HttpResponse response,
    int statusCode,
    Map<String, dynamic> data,
  ) async {
    response.statusCode = statusCode;
    response.headers.contentType = ContentType.json;

    response.write(
      jsonEncode(data),
    );

    await response.close();
  }
}