name: personal_streaming_backend
description: Backend for the personal streaming service.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  password_guard: ^1.0.5
  mailer: ^6.1.2