-- Account-owned TV channel + content intelligence persistence.
-- Channels are created by the account. The scheduler may regenerate schedules
-- only from the contents assigned to each account-owned channel. No themed
-- channel catalog is generated by the platform.
--
-- pgcrypto is enabled by the platform_and_games.sql migration.

create table if not exists public.tv_channel_definitions (
  id uuid text primary key,
  account_id uuid,
  name text not null,
  description text not null default '',
  filters jsonb not null default '[]'::jsonb,
  content_types jsonb not null default '["Movies", "Shows"]'::jsonb,
  seasonal boolean not null default false,
  priority integer not null default 0,
  programming_rules jsonb not null default '[]'::jsonb,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tv_content_intelligence (
  media_id text primary key,
  account_id uuid,
  genres jsonb not null default '[]'::jsonb,
  tags jsonb not null default '[]'::jsonb,
  studios jsonb not null default '[]'::jsonb,
  companies jsonb not null default '[]'::jsonb,
  franchises jsonb not null default '[]'::jsonb,
  holidays jsonb not null default '[]'::jsonb,
  audiences jsonb not null default '[]'::jsonb,
  themes jsonb not null default '[]'::jsonb,
  is_episode boolean not null default false,
  is_movie boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists public.tv_program_schedules (
  id uuid primary key default gen_random_uuid(),
  account_id uuid,
  profile_id uuid,
  channel_id text not null,
  generated_at timestamptz not null default now(),
  season text,
  lineup jsonb not null default '[]'::jsonb,
  constraint tv_program_schedules_account_profile_channel_unique
    unique (account_id, profile_id, channel_id)
);

create index if not exists idx_tv_channel_definitions_account
  on public.tv_channel_definitions(account_id);

create index if not exists idx_tv_content_intelligence_account
  on public.tv_content_intelligence(account_id);

create index if not exists idx_tv_program_schedules_profile
  on public.tv_program_schedules(profile_id);
